### ISSUE TITLE
Pulsing (and thanks)

### ISSUE THREAD

**Issue by buggedcom** [alexeden/rpi-led-matrix#1]
Thank you for this library. It is by far the best for controlling a LED matrix via node. All the others I've tried are buggy with my matrix but this worked out of the box with one of the lowest CPU footprints too. Fantastic work.

I'm using your library as a basis for creating a REST server for controlling the matrix's and adding various api features such as a scribble pad, weather announcements etc.

I've one request, and if I knew C I would create a pull request for it as I have it implemented in node but I am running into CPU limitations of `setInterval`. I would like the ability to "pulse" a pixel via node.

My js code is this...

```js
function setLightPercentage(col, p) {
    const black_level = (100 - p)/100;
    const darkened = col.mix(black, black_level);
    return darkened.rgb();
}

{
//... snip
            _pulseInterval:null,
            _pulseCounter:0,
            _pulseSpeed:null,
            _pulseUpdate() {
                this._pulseCounter++;

                console.log(this._pulseCounter);
                const rgbNumber = this._shadedColours[this._pulseCounter - 1];

                matrix.fgColor(rgbNumber);
                matrix.setPixel(this.x, this.y);
                matrix.sync();

                if(this._pulseCounter >= 10) {
                    this._pulseCounter = 0;
                }
            },
            _generatePulseColours() {
                this._shadedColours = [];
                for(let counter=0, shade; counter < 10; counter++) {
                    if (counter <= 5) {
                        shade = counter * 20;
                    } else {
                        shade = 0 - ((counter - 10) * 20);
                    }
                    this._shadedColours.push(
                        setLightPercentage(this._colour, shade).rgbNumber()
                    );
                }
            },
            pulse(pulses_per_second, r, g, b) {
                this.pulseStop();

                if(typeof r !== 'undefined') {
                    this.r = r;
                    this.g = g;
                    this.b = b;
                }
                this._updateColourFromRgb();

                this._generatePulseColours(pulses_per_second);
                this._pulseSpeed = pulses_per_second;
                this._pulseInterval = setInterval(this._pulseUpdate.bind(this), 100)
            },
            pulseStop() {
                if(this._pulseInterval) {
                    clearInterval(this._pulseInterval);
                    this._pulseInterval = null;
                }
                this._pulseCounter = 0;
            },
//... snip
}
```

It gets bogged down with `setInterval`'s with around 20-30 pixels. I'm guessing there must be a better way to do this via C?

https://www.dropbox.com/s/10znl7aorc6i5r2/VID_20190612_010550.mp4?dl=0

**Comment by alexeden** [comment]
Hey @buggedcom I'm really glad you like the library! I'll see if I can get around to it this weekend. Quite frankly I'm not all that great at C either, but I like a challenge. Plus, it's a cool feature.

**Comment by alexeden** [comment]
Hi again @buggedcom. 

I've added a way to provide the matrix with a callback function that'll get called after each sync and documented it in the [README.](https://github.com/alexeden/rpi-led-matrix)

I took your example and [created something similar. (video)](https://apemedia.s3.us-east-2.amazonaws.com/twinkle720.mp4) Hopefully this is the kind of effect you had in mind. It seems to run smoothly on a 256x32 display.

Sidenote: Part of the reason you were having latency issues is that the call to `.sync()` is the only method that actually does anything hardware-wise, so it's an expensive call. You'll generally want to modify the internal canvas using the `LedMatrixInstance` methods, then only call `.sync()` when you're ready to push the data out. Also, I discovered while creating the pulser demo that the color conversion functions from the `color` package add _a lot_ of overhead. I suppose if you really need them you could memoize and cache the results. Just a thought.

Let me know if this works for you!

**Comment by buggedcom** [comment]
My apologies. I've only just realised this was replied to. I've started to get back into the matrix. I see the example you have created, it looks interesting. Thank you. I will check it out.
