### ISSUE TITLE
Error: A number was expected

### ISSUE THREAD

**Issue by AldrichMascarenhas** [alexeden/rpi-led-matrix#14]
Hey,

I've got a reallt weird error that's been troubling me for weeks now.

The repository is at : 
https://github.com/AldrichMascarenhas/let-there-be-light

I'm running this on a PI 3
pi@raspberrypi:~/Documents/let-there-be-light $ node -v
v12.20.1
pi@raspberrypi:~/Documents/let-there-be-light $ npm -v
6.14.10
pi@raspberrypi:~/Documents/let-there-be-light $ 

<img width="691" alt="Screenshot 2021-02-07 at 18 30 33" src="https://user-images.githubusercontent.com/11980185/107155841-914f1780-6972-11eb-96af-2d47201c0ba4.png">

I've copied the map.ts file but it doesn't seem to work in my local project.
Running "rpi-led-matrix" github project locally seems to work though.

**Comment by alexeden** [comment]
Hey @AldrichMascarenhas, the repo you linked to was either deleted or is private. 😕
FWIW I don't _think_ I've ever seen this error, but I'm more than happy to look into it.

**Comment by alexeden** [comment]
Closing this for now. @AldrichMascarenhas if you continue to see the issue and have a repo that I can test with, feel free to reopen!
