### ISSUE TITLE
how to make layer

### ISSUE THREAD

**Issue by K0rkunc** [alexeden/rpi-led-matrix#15]
hi how to make layers i want play animation over text ?

**Comment by alexeden** [comment]
@K0rkunc I might need more specifics regarding what you're hoping to accomplish, but creating animations with text shouldn't be an issue. You might need to create your own abstractions for managing the graphics (this library doesn't have any notions of a "layer"-like primitive). 

I'd imagine that if you can create what you want in the browser using the Canvas API, it shouldn't be hard to port over to use the matrix API (maybe checkout out the [kitchen sink](https://github.com/alexeden/rpi-led-matrix/blob/master/examples/kitchen-sink.ts) example for reference) on the actual matrix hardware. If the matrix API doesn't quite provide what you need, the `drawBuffer` method will allow you to just dump a buffer of RGB data onto the display. ([example of that here](https://github.com/alexeden/rpi-led-matrix/blob/master/examples/kitchen-sink.ts))

Closing this; but feel free to follow-up with anymore question!
