### ISSUE TITLE
Using buttons along with RGB matrix display

### ISSUE THREAD

**Issue by msurguy** [alexeden/rpi-led-matrix#20]
Hi! Thank you for this amazing library! 

I was wondering if you could provide any pointers on how to use push buttons along with the RGB matrix. It appears that the RGB matrix is blocking access to other GPIOs and I could not read status of the other pins. I'm just trying to hook up a couple buttons and read their status, and do something on the LED matrix when button is pushed.

As I understand, maybe sequence of GPIO initialization matters and I see reference to `SetGPIO` in the files, but no interface described.

Thank you!

**Comment by alexeden** [comment]
Hey Maksim, that's a really good question... I've somehow never even tried to use GPIO for other purposes (e.g. a button) while running a display. I _think_ (don't quote me), running a matrix does unfortunately consume all GPIO resources, but I'm really not sure. Your best bet might be to check out the [original base library](https://github.com/hzeller/rpi-rgb-led-matrix), which is the software actually responsible for interacting with the low-level GPIO peripherals.

Sorry I couldn't be of more use.

**Comment by wesleytabaka** [comment]
@msurguy ,

I had this issue as well using Alex's library until I dug into the original library like @alexeden mentioned.

I was using an npm library called onoff which lets you control GPIO and stuff.  When I would try to drive the LED board with rpi-led-matrix and a button with onoff at the same time it would complain about not having permission at some file that drives the GPIO hardware.

The trick for me was to set the obscure "dropPrivileges": 0 in the RuntimeOptions.  This is part of Henner Zeller's library, rpi-rgb-led-matrix.

I hope this helps!

For example, on the third line from the bottom...

```typescript
const matrix = new LedMatrix(
  {
    ...LedMatrix.defaultMatrixOptions(),
    rows: 32,
    cols: 64,
    chainLength: 2,
    hardwareMapping: GpioMapping.AdafruitHatPwm,
    pixelMapperConfig: LedMatrixUtils.encodeMappers({ type: PixelMapperType.U }),
  },
  {
    ...LedMatrix.defaultRuntimeOptions(),
    gpioSlowdown: 1,
    dropPrivileges: 0
  }
);
```

By the way, thanks Alex for this great library!
