### ISSUE TITLE
Display Images with this Library

### ISSUE THREAD

**Issue by henri-ngl** [alexeden/rpi-led-matrix#21]
Good morning/afternoon, 
First off all thank you for this amazing library.

I'm trying to display images to the LedMatrix with your Library, can you please give me the best approach for that?

I've tried several things but nothing works

Thank you.

**Comment by alexeden** [comment]
Hello, there's nothing provided out-of-the-box for taking for instance a PNG image and drawing it to a matrix (there're too many implementation details involved in such an operation and its well beyond the scope of the library).

But, you can use the `drawBuffer` method on a matrix, which lets you write every single pixel of the display at once using a single `Buffer` of data. [Example here.](https://github.com/alexeden/rpi-led-matrix/blob/master/examples/draw-buffer.ts)

There should be plenty of other libraries out there to help you convert an image file into raw RGB data for writing. 😀

**Comment by henri-ngl** [comment]
Thank you Alex.

I will try it and let you know.

**Comment by curtis-j-campbell** [comment]
Hi @henri-ngl, did you manage to find a library for converting images to RGB data in js?

**Comment by curtis-j-campbell** [comment]
Hi @henri-ngl, did you manage to find a solution / library that allowed you to display images?
