### ISSUE TITLE
Segmentation fault when attempting to run examples

### ISSUE THREAD

**Issue by abwilson2020** [alexeden/rpi-led-matrix#23]
I just installed the library to a new folder on my raspberry pi 4, did npm i and when I run the sudo npm run example -- examples/text-layout-cli.ts command I get the message "Must run as root to be able to access /dev/mem Prepend 'sudo' to the command Segmentation fault"

Any ideas how to fix this to get the examples to work?

**Comment by alexeden** [comment]
Hi Andrew. That's...weird. I've gotten segmentation faults before it's been very rare and ostensibly non-deterministic. Do you get the error every time you try running? 

I haven't played with the library in months so I'll try to spin it up this weekend on a fresh image and see what happens.

**Comment by abwilson2020** [comment]
Yes it appears to be happening each time I attempt to run the example. I did just try this in a new folder just to re-do the installation. When downloading I also made sure to do the recurse submodules. 

Let me know if you get it working on your end. I'll try to answer any questions you have. Thanks!

**Comment by abwilson2020** [comment]
Did you have any luck getting it up and running?

I am still running into issues getting this working.

**Comment by abwilson2020** [comment]
Still having issues with getting this started. I am sure it is something simple I am missing. I am not very familiar with typescript unfortunately. I attempted to use the nodejs version of the library but there is a compilation error in the latest version and it doesn't seem to be maintained anymore sadly.

If you have a discord and would be able to try troubleshooting this with me I would appreciate it. My account is CipherGraphics#6402. If you dont have time I completely understand

**Comment by wesleytabaka** [comment]
Hi @abwilson2020 ,

I'm on a Raspberry Pi 3 running Raspbian codename Buster, but I'd imagine the setup would be the same.

I just cloned the repo and got it working.

There might be some TS setup/assumptions that you're missing.  Maybe these steps will help you find what could be missing:
- Install Node.js with npm.  I happen to be running Node v12.18.1 and npm 6.14.5 on my Pi.  You've probably already done this.
- Install C and C++ compilers of your choice.  I believe I'm using clang.  You've probably already done this.
- Run the following: npm install typescript rimraf node-gyp -g
    (The -g is important.)
- Run the following: git clone https://github.com/alexeden/rpi-led-matrix.git --recurse-submodules
- cd into the cloned repository (cd rpi-led-matrix)
- Run npm install
    This is the critical step.  Along with installing all the node dependencies, this step builds the native binaries.  If this step fails for you report back with your errors.  It will probably have some compiler warnings.  So long as it doesn't error out you should be golden.
- Run npm run build
    This transpiles the typescript of this repository into javascript.  (I think it also rebuilds the binaries from the previous step, so be patient!  Again, you should see no errors but may get some warnings.)
- Try the npm run example -- examples/text-layout-cli.ts again.

Hopefully this helps.

**Comment by konstk1** [comment]
I just set this up on my Pi Zero W2. The examples run mostly fine without `sudo` but using `sudo` causes seg fault.

When I say mostly fine without `sudo`, sometimes examples do crash but it's sporadic.

**Comment by konstk1** [comment]
Rather than using examples, I ended up adding this package as a module to my own application. I saw same crashes when trying to run `sudo npm ....`. This seems to be related to node and not necessarily this package. If I build my typescript and then run `sudo node dist/index.js`, everything runs just fine. 

Similar with `nodemon`, you can't run `sudo nodemon`. This worked for me: `nodemon -w dist --exec "sudo node dist/index.js"`
