### ISSUE TITLE
How to use ledLimitRefresh ?

### ISSUE THREAD

**Issue by alevecchio** [alexeden/rpi-led-matrix#25]
There is any way to add support to ledLimitRefresh like on hzeller library?

--led-limit-refresh=<Hz>  : Limit refresh rate to this frequency in Hz. Useful to keep a
                            constant refresh rate on loaded system. 0=no limit. Default: 0

**Comment by alexeden** [comment]
Hi @alevecchio, sorry this took so long.
Support for the option's been added in [1.13.0](https://github.com/alexeden/rpi-led-matrix/releases/tag/v1.13.0).
