### ISSUE TITLE
Drawing text longer than 14 characters results in weird characters

### ISSUE THREAD

**Issue by konstk1** [alexeden/rpi-led-matrix#26]
When calling `drawText('12345678901234')` with a string of 14 characters, the string prints correctly. However, when I do this with 15 or more characters `drawText('123456789012345')`, the first few characters of the shown string on the display are some garbage characters.

My test code below:

```      
        const fontName = '6x10';
        const font = new Font(fontName, `${process.cwd()}/node_modules/rpi-led-matrix/fonts/${fontName}.bdf`);
        matrix && matrix.brightness(20);
        matrix
            .font(font)
            .fgColor(0xFFFFFF)
            .drawText('123456789012345', 0, 0)
            .sync();
```

**Comment by srcastor** [comment]
> When calling `drawText('12345678901234')` with a string of 14 characters, the string prints correctly. However, when I do this with 15 or more characters `drawText('123456789012345')`, the first few characters of the shown string on the display are some garbage characters.
> 
> My test code below:
> 
> ```
>         const fontName = '6x10';
>         const font = new Font(fontName, `${process.cwd()}/node_modules/rpi-led-matrix/fonts/${fontName}.bdf`);
>         matrix && matrix.brightness(20);
>         matrix
>             .font(font)
>             .fgColor(0xFFFFFF)
>             .drawText('123456789012345', 0, 0)
>             .sync();
> ```

Any progress here? I have the same problem but with 6 characters, appears to be font dependent (using a big one)

**Comment by konstk1** [comment]
I imagine it has to do with screen size. Also, if you're using Unicode characters, those can take up more 1 byte and that counts towards the length.

**Comment by srcastor** [comment]
It could be, 64px x4 chain width (so 256x64px) and just raw numbers 123456

**Comment by konstk1** [comment]
I was able to work around this by splitting the text into smaller segments and drawing them separately. See here: https://github.com/konstk1/matrix-dash/blob/main/src/widgets/text-widget.ts.

**Comment by alexeden** [comment]
@konstk1 Sorry for the delay; I'm finally getting back into updating this library. I plan on doing a major version update with a new API for most drawing operations. I'm going to take the work you did for your `text-widget` and either integrate into the matrix API, or, at a minimum, condense it into an example. Thanks for you work!
