### ISSUE TITLE
add --led-panel-type

### ISSUE THREAD

**Issue by srcastor** [alexeden/rpi-led-matrix#27]
Any way/trick to force --led-panel-type=FM6126A option? 

> There are some panels that have a different chip-set than the default HUB75. These require some initialization sequence. The current supported types are --led-panel-type=FM6126A and --led-panel-type=FM6127

**Comment by alexeden** [comment]
Hi @srcastor, I added support for this option in [1.14.0](https://github.com/alexeden/rpi-led-matrix/releases/tag/v1.14.0).
I'll caveat this though and say that I don't (think) I have any panels that have ever required this option to be set, so I'm not able to physically test it; but, the value specified should definitely be passed down to the underlying library.
