### ISSUE TITLE
Incorrect options mapping

### ISSUE THREAD

**Issue by whalemare** [alexeden/rpi-led-matrix#4]
Hello. 
I am add new feature to original [rpi-rgb-led-matrix](https://github.com/hzeller/rpi-rgb-led-matrix) (adding new multiplexing mode) that stored into `/vendor` directory.
After that I am build changes, to check that all works correctly:
```bash
cd vendor
make
npm run build
cd ..
``` 

When sources builded I am run it directly (without js layer)
```bash
sudo ./vendor/examples-api-use/scrolling-text-example --led-inverse --led-rows=16 -s 2 -f fonts/8x13.bdf 0000 --led-multiplexing=9
```
I am see scrolling "0000" without any glitches. (Please, note that argument `9` in param `--led-multiplexing` for now it is refactored multiplexing class)
![2019-10-09 18 20 17](https://user-images.githubusercontent.com/9128731/66477148-8b68ce00-eac1-11e9-896b-a93078fdcf48.jpg)

After that, I trying to run `examples/text-layout-cli.ts`.
Checking that `_config.ts` settings equals with settings configured via CLI before.
```ts
import {
  LedMatrix,
  MatrixOptions,
  RuntimeOptions,
} from '../src';

export const matrixOptions: MatrixOptions = {
  ...LedMatrix.defaultMatrixOptions(),
  rows: 16,
  inverseColors: true,
  multiplexing: 9,
};

export const runtimeOptions: RuntimeOptions = {
  ...LedMatrix.defaultRuntimeOptions(),
};
```

and run 
```bash
sudo npm run example -- examples/text-layout-cli.ts
```
 For now, I see glitched text (I am think, it is because incorrect set multiplexing.)
![has glitches](https://user-images.githubusercontent.com/9128731/66476964-244b1980-eac1-11e9-9be1-58d1f54d92f5.jpg)

**Comment by alexeden** [comment]
Hey Anton, sorry for the delay in response. The stuff inside of `/vendor` is pulled as a git submodule from the original library by hzeller. Given that this library is just a binding wrapper around it, it makes sense that changing the original library will break things. It sounds like (I think) you'll need to open a PR on hzeller's repo, at which point I'm more than happy to adapt this library to accommodate the changes. If you think I'm mistaken though, feel free to email me directly and we can work through it. I'm interested in seeing the changes you made to the C++ code as that might lead to an easy solution on the TS side of things.
